name: Test All Modules

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get Packages
      run: go mod download
      working-directory: ./oauth2-bro

    - name: Test All Modules
      run: |
        find . -name "go.mod" -type f | while read -r modfile; do
          module_dir=$(dirname "$modfile")
          echo "Testing module: $module_dir"
          cd "$module_dir" && go test ./... && cd - > /dev/null
        done

    - name: Build Application
      run: go build -ldflags="-X 'main.version=CI'" -o oauth2-bro
      working-directory: ./oauth2-bro

    - name: Test Docker Build
      run: docker build -t oauth2-bro-ci .
